"""Initial migration.

Revision ID: d1c967e4f4fc
Revises: 
Create Date: 2025-07-27 09:46:45.950889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c967e4f4fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('tipo_anotacao',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_pai_nome', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tipo_pai_nome'], ['tipo_anotacao.nome'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('universo',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('ultima_edicao', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('evento',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('razao_inicio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['nome'], ['tipo_anotacao.nome'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('lugar',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tamanho', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['nome'], ['tipo_anotacao.nome'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('template_anot',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_padrao_nome', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tipo_padrao_nome'], ['tipo_anotacao.nome'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('anotacao',
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('ultima_edicao', sa.Date(), nullable=True),
    sa.Column('nuniverso', sa.String(length=100), nullable=True),
    sa.Column('tipo_anota', sa.String(length=100), nullable=True),
    sa.Column('ntemplate_anot', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ntemplate_anot'], ['template_anot.nome'], ),
    sa.ForeignKeyConstraint(['nuniverso'], ['universo.nome'], ),
    sa.ForeignKeyConstraint(['tipo_anota'], ['tipo_anotacao.nome'], ),
    sa.PrimaryKeyConstraint('titulo')
    )
    op.create_table('catego_anotacao',
    sa.Column('ncategoria', sa.String(length=100), nullable=False),
    sa.Column('nanotacao', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['nanotacao'], ['anotacao.titulo'], ),
    sa.ForeignKeyConstraint(['ncategoria'], ['categoria.nome'], ),
    sa.PrimaryKeyConstraint('ncategoria', 'nanotacao')
    )
    op.create_table('mencoes',
    sa.Column('anot_mencionada', sa.String(length=100), nullable=False),
    sa.Column('anot_mencionando', sa.String(length=100), nullable=False),
    sa.Column('palavra_chave', sa.String(length=100), nullable=True),
    sa.Column('posicao_no_texto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anot_mencionada'], ['anotacao.titulo'], ),
    sa.ForeignKeyConstraint(['anot_mencionando'], ['anotacao.titulo'], ),
    sa.PrimaryKeyConstraint('anot_mencionada', 'anot_mencionando')
    )
    op.create_table('propriedade',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('chave_valor', sa.JSON(), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('valor_bruto', sa.Text(), nullable=True),
    sa.Column('nanotacao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nanotacao'], ['anotacao.titulo'], ),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('tabela',
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('titu_anotacao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['titu_anotacao'], ['anotacao.titulo'], ),
    sa.PrimaryKeyConstraint('titulo')
    )
    op.create_table('coluna',
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('ttabela', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ttabela'], ['tabela.titulo'], ),
    sa.PrimaryKeyConstraint('titulo', 'ttabela')
    )
    op.create_table('duracao',
    sa.Column('nprop', sa.String(length=100), nullable=False),
    sa.Column('desc_periodo', sa.Text(), nullable=True),
    sa.Column('nevento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nevento'], ['evento.nome'], ),
    sa.ForeignKeyConstraint(['nprop'], ['propriedade.nome'], ),
    sa.PrimaryKeyConstraint('nprop')
    )
    op.create_table('linha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ttabela', sa.String(length=100), nullable=False),
    sa.Column('celulas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ttabela'], ['tabela.titulo'], ),
    sa.PrimaryKeyConstraint('id', 'ttabela')
    )
    op.create_table('localizacao',
    sa.Column('nprop', sa.String(length=100), nullable=False),
    sa.Column('pontos_referencia', sa.Text(), nullable=True),
    sa.Column('nlugar', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['nlugar'], ['lugar.nome'], ),
    sa.ForeignKeyConstraint(['nprop'], ['propriedade.nome'], ),
    sa.PrimaryKeyConstraint('nprop')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localizacao')
    op.drop_table('linha')
    op.drop_table('duracao')
    op.drop_table('coluna')
    op.drop_table('tabela')
    op.drop_table('propriedade')
    op.drop_table('mencoes')
    op.drop_table('catego_anotacao')
    op.drop_table('anotacao')
    op.drop_table('template_anot')
    op.drop_table('lugar')
    op.drop_table('evento')
    op.drop_table('universo')
    op.drop_table('tipo_anotacao')
    op.drop_table('categoria')
    # ### end Alembic commands ###
